#!/bin/sh

# Set these paths appropriately

BIN=/Users/youyuan/Documents/Courses/cs124/pa/pa6-mt/translate/util/tree-tagger/bin
CMD=/Users/youyuan/Documents/Courses/cs124/pa/pa6-mt/translate/util/tree-tagger/cmd
LIB=/Users/youyuan/Documents/Courses/cs124/pa/pa6-mt/translate/util/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
