#!/bin/sh

# Set these paths appropriately

BIN=/Users/youyuan/Documents/Courses/cs124/pa/pa6-mt/translate/util/tree-tagger/bin
CMD=/Users/youyuan/Documents/Courses/cs124/pa/pa6-mt/translate/util/tree-tagger/cmd
LIB=/Users/youyuan/Documents/Courses/cs124/pa/pa6-mt/translate/util/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
